# Netlify configuration file for deploying a Vite + React project
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://api-pos.kokotoa.online/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "https://api-pos.kokotoa.online/media/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://api-pos.kokotoa.online/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
